Update .github/workflows/auto-release-tag.yml
Co-authored-by: Victor Martinez <victormartinezrubio@gmail.com>

diff --git a/.github/workflows/auto-release-tag.yml b/.github/workflows/auto-release-tag.yml
--- a/.github/workflows/auto-release-tag.yml
+++ b/.github/workflows/auto-release-tag.yml
@@ -15,10 +15,11 @@ jobs:
           if [[ ${{ github.head_ref }} =~ ^release/([0-9]+\.[0-9]+\.[0-9]+$) ]]; then
             echo "match=true" >> $GITHUB_OUTPUT
             echo "version=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
+          elif [[ "${{ github.event.pull_request.merged }} != "true" ]] ; then
+            FAILURE_MESSAGE='Tag if release branch'
+            echo "FAILURE_MESSAGE=${FAILURE_MESSAGE}" >> "$GITHUB_ENV"
+            echo "::error::${FAILURE_MESSAGE}" ; exit 1
           fi
-      - name: Tag if release branch
-        if: github.event.pull_request.merged != true || steps.check-release.outputs.match != 'true'
-        run: exit 1
       - uses: actions/checkout@v4
         with:
           ref: ${{ github.event.pull_request.merge_commit_sha }}
